export class names {
    fullname: string;
    firstname: string;
    lastname: string;
}

/*
{  
    "report_info":{  
       "query_id":null,
       "report_id":"169c410a-734f-4cac-b9be-d97149b8a806",
       "response_time":0.180540049,
       "proxy_flags":[  
 
       ]
    },
    "bvids":[  
 
    ],
    "names":[  
       {  
          "full":"R**** H ****",
          "parts":{  
             "salutation":"",
             "first_name":"R****",
             "middle_name":"H",
             "last_name":"****",
             "suffix":""
          },
          "first_seen":"",
          "last_seen":""
       },
       {  
          "full":"S**** ****",
          "parts":{  
             "salutation":"",
             "first_name":"S****",
             "middle_name":"",
             "last_name":"****",
             "suffix":""
          },
          "first_seen":"",
          "last_seen":""
       }
    ],
    "addresses":[  
       {  
          "latitude":40.714167,
          "longitude":-74.006389,
          "precision":"city",
          "property_record_available":null,
          "full":"New York, NY",
          "parts":{  
             "house_number":"",
             "pre_direction":"",
             "street_name":"",
             "street_type":"",
             "post_direction":"",
             "unit":"",
             "city":"New York",
             "state":"NY",
             "zip":"",
             "zip4":"",
             "country":"US"
          },
          "type":"",
          "first_seen":"",
          "last_seen":""
       },
       {  
          "latitude":43.661389,
          "longitude":-70.255833,
          "precision":"city",
          "property_record_available":null,
          "full":"Portland, ME",
          "parts":{  
             "house_number":"",
             "pre_direction":"",
             "street_name":"",
             "street_type":"",
             "post_direction":"",
             "unit":"",
             "city":"Portland",
             "state":"ME",
             "zip":"",
             "zip4":"",
             "country":"US"
          },
          "type":"",
          "first_seen":"",
          "last_seen":""
       },
       {  
          "latitude":43.083056,
          "longitude":-73.785,
          "precision":"city",
          "property_record_available":null,
          "full":"Saratoga Springs, NY",
          "parts":{  
             "house_number":"",
             "pre_direction":"",
             "street_name":"",
             "street_type":"",
             "post_direction":"",
             "unit":"",
             "city":"Saratoga Springs",
             "state":"NY",
             "zip":"",
             "zip4":"",
             "country":"US"
          },
          "type":"",
          "first_seen":"",
          "last_seen":""
       },
       {  
          "latitude":40.714167,
          "longitude":-74.006389,
          "precision":"city",
          "property_record_available":null,
          "full":"New York, NY",
          "parts":{  
             "house_number":"",
             "pre_direction":"",
             "street_name":"",
             "street_type":"",
             "post_direction":"",
             "unit":"",
             "city":"New York",
             "state":"NY",
             "zip":"",
             "zip4":"",
             "country":"US"
          },
          "type":"",
          "first_seen":"",
          "last_seen":""
       }
    ],
    "dob":"",
    "gender":"male",
    "emails":[  
       {  
          "email_address":"xxxxxxxx@gmail.com",
          "type":"personal",
          "address_md5":"9d04ff2cb6e109ee1da2c43106d94765",
          "is_disposable":false,
          "is_public_provider":true,
          "first_seen":"",
          "last_seen":""
       },
       {  
          "email_address":"xxxxxx@f****.com",
          "type":"work",
          "address_md5":"dc9e519cd754b72f3f0ae27cd7a0fc0a",
          "is_disposable":false,
          "is_public_provider":false,
          "first_seen":"",
          "last_seen":""
       },
       {  
          "email_address":"xxxxxx@s****.edu",
          "type":"",
          "address_md5":"d611be79681237c586e77b3d38ec901b",
          "is_disposable":false,
          "is_public_provider":false,
          "first_seen":"",
          "last_seen":""
       }
    ],
    "phones":[  
       {  
          "number":"207615XXXX",
          "type":"mobile",
          "first_seen":"",
          "last_seen":"",
          "country_code":1
       },
       {  
          "number":"646882XXXX",
          "type":"",
          "first_seen":"",
          "last_seen":"",
          "country_code":1
       },
       {  
          "number":"212785XXXX",
          "type":"",
          "first_seen":"",
          "last_seen":"",
          "country_code":1
       }
    ],
    "jobs":[  
 
    ],
    "educations":[  
 
    ],
    "images":[  
 
    ],
    "social":[  
 
    ],
    "user_ids":[  
       "97****@linkedin",
       "28****@linkedin",
       "18****@gravatar",
       "12****@facebook",
       "#8****@linkedin"
    ],
    "usernames":[  
       "sk****",
       "rs****"
    ],
    "languages":[  
       {  
          "language":"en",
          "region":"US"
       }
    ],
    "ethnicities":[  
 
    ],
    "origin_countries":[  
 
    ]
 }
 */